/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DegenDealsERC6551RegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "account"
      | "createAccount"
      | "createDealAccount"
      | "dealAccountImplementations"
      | "dealAccounts"
      | "degenDeals"
      | "degenDealsERC6551Account"
      | "deriveCreateDealAccount"
      | "entryPoint"
      | "initialize"
      | "owner"
      | "setDegenDealsERC6551Account"
      | "setEntryPoint"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ERC6551AccountCreated" | "Initialized"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "account",
    values: [AddressLike, BytesLike, BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createAccount",
    values: [AddressLike, BytesLike, BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createDealAccount",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "dealAccountImplementations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dealAccounts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "degenDeals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "degenDealsERC6551Account",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deriveCreateDealAccount",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "entryPoint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setDegenDealsERC6551Account",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setEntryPoint",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "account", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createDealAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dealAccountImplementations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dealAccounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "degenDeals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "degenDealsERC6551Account",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deriveCreateDealAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "entryPoint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDegenDealsERC6551Account",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEntryPoint",
    data: BytesLike
  ): Result;
}

export namespace ERC6551AccountCreatedEvent {
  export type InputTuple = [
    account: AddressLike,
    implementation: AddressLike,
    salt: BytesLike,
    chainId: BigNumberish,
    tokenContract: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [
    account: string,
    implementation: string,
    salt: string,
    chainId: bigint,
    tokenContract: string,
    tokenId: bigint
  ];
  export interface OutputObject {
    account: string;
    implementation: string;
    salt: string;
    chainId: bigint;
    tokenContract: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DegenDealsERC6551Registry extends BaseContract {
  connect(runner?: ContractRunner | null): DegenDealsERC6551Registry;
  waitForDeployment(): Promise<this>;

  interface: DegenDealsERC6551RegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  account: TypedContractMethod<
    [
      implementation: AddressLike,
      salt: BytesLike,
      chainId: BigNumberish,
      tokenContract: AddressLike,
      tokenId: BigNumberish
    ],
    [string],
    "view"
  >;

  createAccount: TypedContractMethod<
    [
      implementation: AddressLike,
      salt: BytesLike,
      chainId: BigNumberish,
      tokenContract: AddressLike,
      tokenId: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  createDealAccount: TypedContractMethod<
    [dealId: BigNumberish, implementation: AddressLike],
    [string],
    "nonpayable"
  >;

  dealAccountImplementations: TypedContractMethod<
    [dealId: BigNumberish],
    [string],
    "view"
  >;

  dealAccounts: TypedContractMethod<[dealId: BigNumberish], [string], "view">;

  degenDeals: TypedContractMethod<[], [string], "view">;

  degenDealsERC6551Account: TypedContractMethod<[], [string], "view">;

  deriveCreateDealAccount: TypedContractMethod<
    [dealId: BigNumberish, splitDealId: BigNumberish],
    [string],
    "nonpayable"
  >;

  entryPoint: TypedContractMethod<[], [string], "view">;

  initialize: TypedContractMethod<
    [
      degenDeals_: AddressLike,
      degenDealsERC6551Account_: AddressLike,
      entryPoint_: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  setDegenDealsERC6551Account: TypedContractMethod<
    [degenDealsERC6551Account_: AddressLike],
    [void],
    "nonpayable"
  >;

  setEntryPoint: TypedContractMethod<
    [entryPoint_: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "account"
  ): TypedContractMethod<
    [
      implementation: AddressLike,
      salt: BytesLike,
      chainId: BigNumberish,
      tokenContract: AddressLike,
      tokenId: BigNumberish
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "createAccount"
  ): TypedContractMethod<
    [
      implementation: AddressLike,
      salt: BytesLike,
      chainId: BigNumberish,
      tokenContract: AddressLike,
      tokenId: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createDealAccount"
  ): TypedContractMethod<
    [dealId: BigNumberish, implementation: AddressLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "dealAccountImplementations"
  ): TypedContractMethod<[dealId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "dealAccounts"
  ): TypedContractMethod<[dealId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "degenDeals"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "degenDealsERC6551Account"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deriveCreateDealAccount"
  ): TypedContractMethod<
    [dealId: BigNumberish, splitDealId: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "entryPoint"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      degenDeals_: AddressLike,
      degenDealsERC6551Account_: AddressLike,
      entryPoint_: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setDegenDealsERC6551Account"
  ): TypedContractMethod<
    [degenDealsERC6551Account_: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setEntryPoint"
  ): TypedContractMethod<[entryPoint_: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ERC6551AccountCreated"
  ): TypedContractEvent<
    ERC6551AccountCreatedEvent.InputTuple,
    ERC6551AccountCreatedEvent.OutputTuple,
    ERC6551AccountCreatedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;

  filters: {
    "ERC6551AccountCreated(address,address,bytes32,uint256,address,uint256)": TypedContractEvent<
      ERC6551AccountCreatedEvent.InputTuple,
      ERC6551AccountCreatedEvent.OutputTuple,
      ERC6551AccountCreatedEvent.OutputObject
    >;
    ERC6551AccountCreated: TypedContractEvent<
      ERC6551AccountCreatedEvent.InputTuple,
      ERC6551AccountCreatedEvent.OutputTuple,
      ERC6551AccountCreatedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
  };
}
