/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as abstract from "./abstract";
export type { abstract };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as mock from "./mock";
export type { mock };
export type { DegenDealsERC20 } from "./DegenDealsERC20";
export type { DegenDealsERC6551Account } from "./DegenDealsERC6551Account";
export type { DegenDealsERC6551Registry } from "./DegenDealsERC6551Registry";
export type { DegenDealsERC721 } from "./DegenDealsERC721";
export type { DegenDealsProxy } from "./DegenDealsProxy";
