/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc4337 from "./ERC4337";
export type { erc4337 };
import type * as erc6551 from "./ERC6551";
export type { erc6551 };
export type { IDegenDealsERC20 } from "./IDegenDealsERC20";
export type { IDegenDealsERC6551Account } from "./IDegenDealsERC6551Account";
export type { IDegenDealsERC6551Registry } from "./IDegenDealsERC6551Registry";
export type { IDegenDealsERC721 } from "./IDegenDealsERC721";
